# Stage 1 : Build React App
FROM node:alpine AS builder
WORKDIR /app
COPY package.json .
RUN ["npm", "install"]
COPY . .
RUN ["npm", "run", "build"]

# Stage 2 : Setup nginx
FROM nginx:alpine

# Copy build file from previous stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
