services:
  traefik:
    image: traefik:v3.1
    container_name: traefik-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"

  server:
    image: josephyusmita/catalyst-server
    env_file: ./server/.env.production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  client:
    image: josephyusmita/catalyst-client
    depends_on:
      - server
    networks:
      - mynetwork

  database:
    image: postgres:latest
    container_name: catalyst_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  letsencrypt:
