services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=josephyusmita@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"

  server:
    image: josephyusmita/catalyst-server
    env_file: ./server/.env.production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`server.catalyst-dev.site`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=le"

  client:
    image: josephyusmita/catalyst-client
    depends_on:
      - server
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`catalyst-dev.site`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=le"

  database:
    image: postgres:latest
    container_name: catalyst_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  letsencrypt:
