services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # HTTP Port
      - "80:80"
      # Dashboard Port
      - "8080:8080"
    volumes:
      # Used so traefik can listen to docker events
      - /var/run/docker.sock:/var/run.docker.sock
  server:
    image: josephyusmita/catalyst-server
    env_file: ./server/.env.production
      - "traefik.http.routers.client.rule=Host(`backend.catalyst-dev.site`)"
      - "traefik.http.services.client.loadbalancer.server.port=8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  client:
    image: josephyusmita/catalyst-client
    labels:
      - "traefik.http.routers.client.rule=Host(`catalyst-dev.site`)"
      - "traefik.http.services.client.loadbalancer.server.port=5000"
    depends_on:
      - server
    networks:
      - mynetwork

  database:
    image: postgres:latest
    container_name: catalyst_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  letsencrypt:
