services:
  server:
    image: josephyusmita/catalyst-server
    ports:
      - 8000:8000
    env_file: ./server/.env.production
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  client:
    image: josephyusmita/catalyst-client
    ports:
      - 80:8080
    depends_on:
      - server
    networks:
      - mynetwork

  database:
    image: postgres:latest
    container_name: catalyst_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mypassword"]
      interval: 5s
      timeout: 2s
      retries: 20

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
