# name: Test SSH Connection

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-ssh:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh
#           printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           eval "$(ssh-agent -s)"
#           ssh-add ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

#       - name: Test SSH Connection
#         run: |
#           ssh -o StrictHostKeyChecking=no joseph@${{ secrets.VM_IP }} "echo 'SSH Connection successful'"
